name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Node dependencies
        run: npm install
      - name: Lint backend
        run: make lint
      - name: Lint frontend
        run: npm run lint
      - name: Type check frontend
        run: npm run typecheck
      - name: Run tests
        run: |
          npm test
          pytest
